---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[java::default]
      - recipe[sch-elasticsearch::default]
    attributes:
      elasticsearch:
        version: 1.2.3
      java:
        install_flavor: "openjdk"
        jdk_version: "7"
